# Generated by Django 2.1.3 on 2018-12-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('Horaio_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('Cod_Materia', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('CI', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Titulo_Profesion', models.CharField(max_length=20)),
                ('Materias_Imparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PNFI.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('Cod_Seccion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='horarios',
            name='B10_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B10_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B10_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B10_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B10_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B10_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B10_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B10_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B10_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B10_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B11_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B11_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B11_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B11_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B11_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B11_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B11_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B11_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B11_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B11_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B1_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B1_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B1_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B1_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B1_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B1_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B1_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B1_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B1_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B1_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B2_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B2_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B2_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B2_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B2_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B2_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B2_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B2_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B2_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B2_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B3_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B3_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B3_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B3_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B3_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B3_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B3_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B3_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B3_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B3_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B4_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B4_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B4_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B4_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B4_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B4_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B4_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B4_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B4_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B4_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B5_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B5_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B5_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B5_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B5_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B5_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B5_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B5_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B5_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B5_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B6_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B6_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B6_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B6_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B6_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B6_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B6_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B6_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B6_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B6_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B7_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B7_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B7_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B7_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B7_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B7_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B7_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B7_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B7_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B7_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B8_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B8_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B8_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B8_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B8_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B8_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B8_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B8_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B8_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B8_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B9_Jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B9_Jueves', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B9_Lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B9_Lunes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B9_Martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B9_Martes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B9_Miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B9_Miercoles', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='B9_Viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='B9_Viernes', to='PNFI.Materia'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Cod_Horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cod_Horario', to='PNFI.Seccion'),
        ),
    ]
