# Generated by Django 2.1.3 on 2018-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNFI', '0002_auto_20181204_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
